# Generated by Django 4.1.7 on 2023-03-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotanicalGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgName', models.CharField(max_length=100, unique=True)),
                ('bgCapacity', models.PositiveIntegerField()),
                ('bgPlants', models.PositiveIntegerField()),
                ('bgYear', models.DateField()),
                ('bgLocation', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
