-- Transaction 2
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
-- SET TRANSACTION ISOLATION LEVEL REPEATABLE READ 
-- solution
BEGIN TRANSACTION
SELECT * FROM theatrical_piece
WAITFOR DELAY '00:00:05'
SELECT * FROM theatrical_piece 
COMMIT TRANSACTION
