# Generated by Django 4.1.7 on 2023-03-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plant_plantparent_alter_worker_workerparent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watching',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='watching',
            old_name='worker_id',
            new_name='worker',
        ),
    ]
