# Generated by Django 4.1.7 on 2023-03-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_plant_id_watching_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watching',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plant'),
        ),
        migrations.AlterField(
            model_name='watching',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.worker'),
        ),
    ]
