# Generated by Django 4.1.7 on 2023-03-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerFirstName', models.CharField(max_length=100)),
                ('workerLastName', models.CharField(max_length=100)),
                ('workerBirthDate', models.DateField()),
                ('workerStartDate', models.DateField()),
                ('workerJob', models.CharField(max_length=100)),
                ('workerParent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.botanicalgarden')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantCommonName', models.CharField(max_length=100, unique=True)),
                ('plantLatinName', models.CharField(max_length=200, unique=True)),
                ('plantLength', models.PositiveIntegerField()),
                ('plantLightLevel', models.PositiveIntegerField()),
                ('plantTemperatureLevel', models.PositiveIntegerField()),
                ('plantSoilType', models.CharField(max_length=100)),
                ('plantHydrationLevel', models.PositiveIntegerField()),
                ('plantAge', models.PositiveIntegerField()),
                ('plantParent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.botanicalgarden')),
            ],
        ),
    ]
