# Generated by Django 4.1.7 on 2023-03-27 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_watching_plant_alter_watching_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botanicalgarden',
            name='bgCapacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='botanicalgarden',
            name='bgPlants',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3000000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plantHydrationLevel',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plantLength',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plantLightLevel',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plantTemperatureLevel',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
